### ISSUE TITLE
Test failure with the development version of tibble

### ISSUE THREAD

**Issue by krlmlr** [ropensci-archive/scrubr#37]
It looks like the tests in this package are sensitive to the order of the `attributes()` in a tibble object, which has changed in tibble 3.1.4. Can you please confirm?

`testthat::expect_equal()` and `testthat::expect_identical()` handle this case automatically, but must be applied on the entire object.

``` r
testthat::expect_equal(
  attributes(structure(list(), a = 1, b = 2)),
  attributes(structure(list(), b = 2, a = 1))
)
#> Error: attributes(structure(list(), a = 1, b = 2)) not equal to attributes(structure(list(), b = 2, a = 1)).
#> Names: 2 string mismatches
#> Component 1: Mean relative difference: 1
#> Component 2: Mean relative difference: 0.5
testthat::expect_equal(
  structure(list(), a = 1, b = 2),
  structure(list(), b = 2, a = 1)
)
```

<sup>Created on 2021-08-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by maelle** [comment]
This repository is about to be archived (and the package was archived on CRAN).
